### ISSUE TITLE
En essayant de mettre a jours le profil et en mettant une adresse mail no valide, app.user passe a null ! 

### ISSUE THREAD

**Issue by billal-lab** [mercuryseries/panterest#4]
![image](https://user-images.githubusercontent.com/77462646/107155360-3e785e80-6978-11eb-8228-1ee3b993f55c.png)
![image](https://user-images.githubusercontent.com/77462646/107155376-4d5f1100-6978-11eb-9a86-639b4ee0b3ad.png)

**Comment by mercuryseries** [comment]
https://stackoverflow.com/questions/18148647/symfony-authentication-issue-after-username-change

**Comment by billal-lab** [comment]
Merci honoré, pour ce lien ça m'a fait savoir des choses intéressante, mais la ils parlent quand les donnée sont changé alors que moi c'est quand on met un mail invalid lors de l'édition. surement y'a une relation entre ces token et mon problème mais j'arrive pas a le localiser...

> https://stackoverflow.com/questions/18148647/symfony-authentication-issue-after-username-change
